### ISSUE TITLE
couldn't recognize data in image file "WeSearch.png"

### ISSUE THREAD

**Issue by syagev** [OfekYarom/We-Search#3]
When trying to run Client.py I get the following exception:

```
D:\Dropbox\Projects\Search-Engine>"C:\Program Files\Python27\python.exe" Client.py
Traceback (most recent call last):
  File "Client.py", line 115, in <module>
    symbol=PhotoImage(file="WeSearch.png")
  File "C:\Program Files\Python27\lib\lib-tk\Tkinter.py", line 3371, in __init__
    Image.__init__(self, 'photo', name, cnf, master, **kw)
  File "C:\Program Files\Python27\lib\lib-tk\Tkinter.py", line 3325, in __init__
    self.tk.call(('image', 'create', imgtype, name,) + options)
_tkinter.TclError: couldn't recognize data in image file "WeSearch.png"
```

I checked and the following returns `True`:
```
>>> import os
>>> exists = os.path.isfile('WeSearch.png')
>>> print exists
True
```
so the file *does* exist but cannot be read for some reason..

I suggest that this error should not stop the application from loading since it's a minor issue - simply don't display the image if something goes wrong.

**Comment by OfekYarom** [comment]
fixed
